"""
webrtc_manager.py — WebRTC connection handling via aiortc

Manages RTCPeerConnections for real-time intent broadcasting (via DataChannels)
and DDSP audio streaming (via RTCAudioTrack).
"""

import asyncio
import logging

from aiortc import RTCDataChannel, RTCPeerConnection, RTCSessionDescription
from aiortc.mediastreams import AudioStreamTrack
from av.audio.frame import AudioFrame

from claudio.intent.intent_protocol import IntentPacket

logger = logging.getLogger(__name__)


class DDSPAudioTrack(AudioStreamTrack):
    """
    A WebRTC audio track that plays raw floating point audio generated by DDSP.
    """
    kind = "audio"

    def __init__(self, sample_rate: int = 44100):
        super().__init__()
        self.sample_rate = sample_rate
        self.buffer = b""
        self.queue = asyncio.Queue()
        self._timestamp = 0

    async def add_audio(self, pcm_float_bytes: bytes):
        """Add floating point audio generated by the DDSP engine."""
        await self.queue.put(pcm_float_bytes)

    async def recv(self) -> AudioFrame:
        """Called by aiortc to pull the next 20ms of audio frame."""
        # 20ms of audio at 48000Hz (aiortc standard) is 960 samples.
        # But we need to handle resampling or just let aiortc handle it.
        # aiortc prefers 48000Hz, 16-bit PCM for audio frames.

        # In a real POC, wait for data in the queue
        try:
            await asyncio.wait_for(self.queue.get(), timeout=0.02)
        except TimeoutError:
            b'\x00' * 960 * 2  # Silence 48kHz 16-bit 1ch

        # For simplicity in this POC, we'll construct an AudioFrame.
        # Normally you would parse the float bytes and convert to s16.
        # Here we assume data is s16 PCM for aiortc, or we return silence if empty.
        # (This is stubbed for the SFU track to be fed by claudio_server)
        frame = AudioFrame(format='s16', layout='mono', samples=960)
        frame.pts = self._timestamp
        frame.sample_rate = 48000
        frame.time_base = 1 / 48000
        self._timestamp += 960
        return frame


class WebRTCManager:
    def __init__(self, session_manager):
        self.session_manager = session_manager
        self.pcs: dict[str, RTCPeerConnection] = {}
        self.tracks: dict[str, DDSPAudioTrack] = {}
        self.data_channels: dict[str, RTCDataChannel] = {}

    async def handle_offer(self, peer_id: str, room_id: str, sdp: str, type: str, global_ddsp_decoder=None):
        pc = RTCPeerConnection()
        self.pcs[peer_id] = pc

        # Create DDSP Audio Track
        # The browser receives this track and plays it natively
        ddsp_track = DDSPAudioTrack()
        self.tracks[peer_id] = ddsp_track
        pc.addTrack(ddsp_track)

        # When peer disconnects via ICE
        @pc.on("iceconnectionstatechange")
        async def on_iceconnectionstatechange():
            if pc.iceConnectionState == "failed" or pc.iceConnectionState == "closed":
                await self.close_peer(peer_id, room_id)

        # Handle incoming intents via DataChannel
        @pc.on("datachannel")
        def on_datachannel(channel: RTCDataChannel):
            self.data_channels[peer_id] = channel

            @channel.on("message")
            async def on_message(message):
                # Message is binary intent packet
                if isinstance(message, bytes):
                    # Broadcast to other peers via WebRTC and WebSocket peers
                    await self._broadcast_intent(peer_id, room_id, message, global_ddsp_decoder)

        # Handle the offer
        offer = RTCSessionDescription(sdp=sdp, type=type)
        await pc.setRemoteDescription(offer)

        # Create answer
        answer = await pc.createAnswer()
        await pc.setLocalDescription(answer)

        return {
            "sdp": pc.localDescription.sdp,
            "type": pc.localDescription.type
        }

    async def _broadcast_intent(self, sender_id: str, room_id: str, data: bytes, global_ddsp_decoder):
        """
        Broadcast intent received via WebRTC to WebSocket users and other WebRTC users.
        """
        room = self.session_manager.get_room(room_id)
        if not room:
            return

        sender_peer = room.peers.get(sender_id)

        # 1. Broadcast via WebSocket paths
        await self.session_manager.broadcast_intent(room_id, sender_id, data)

        # 2. Broadcast to other WebRTC data channels
        await self.broadcast_intent_p2p(room_id, sender_id, data)

        # 3. If DDSP is enabled for the sender, synthesize and push to their WebRTC audio track
        if sender_peer and sender_peer.ddsp_enabled and global_ddsp_decoder:
            packet = IntentPacket.from_bytes(data)
            if packet.frame is not None:
                sender_peer._ddsp_buffer.append(packet.frame)

            if len(sender_peer._ddsp_buffer) >= 12:
                # audio_chunk is float32
                audio_chunk = global_ddsp_decoder.decode_frames(sender_peer._ddsp_buffer)
                sender_peer._ddsp_buffer.clear()

                track = self.tracks.get(sender_id)
                if track:
                    # enqueue audio for transmission
                    await track.add_audio(audio_chunk.tobytes())

    async def broadcast_intent_p2p(self, room_id: str, sender_id: str, data: bytes):
        """
        Broadcast intent to all WebRTC peers in the room except the sender.
        """
        room = self.session_manager.get_room(room_id)
        if not room:
            return

        for pid in room.peers:
            if pid == sender_id:
                continue

            channel = self.data_channels.get(pid)
            if channel and channel.readyState == "open":
                try:
                    channel.send(data)
                except Exception as e:
                    logger.warning(f"Failed to send WebRTC data to peer {pid}: {e}")

    async def close_peer(self, peer_id: str, room_id: str):
        pc = self.pcs.pop(peer_id, None)
        if pc:
            await pc.close()
        self.tracks.pop(peer_id, None)
        self.data_channels.pop(peer_id, None)
        await self.session_manager.leave_room(room_id, peer_id)

